# Generated by Django 5.0.7 on 2024-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_record_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.CharField(max_length=50),
        ),
    ]
